query GET_SOURCE($id: ID!) {
    source(id: $id) {
        data {
            id
            attributes {
                title
                content
                publisher {
                    data {
                        attributes {
                            name
                            site
                        }
                    }
                }
                source
            }
        }
    }
}

mutation ADD_SUMMARY($id: ID!, $summary: JSON!) {
    updateSource(id: $id, data: { summary: $summary }) {
        data {
            attributes {
                summary
            }
        }
    }
}
