query GET_ALL_SOURCES {
    sources {
        data {
            id
            attributes {
                title
                content
                createdAt

                publisher {
                    data {
                        attributes {
                            name
                            site
                        }
                    }
                }
            }
        }
    }
}
