query GET_SOURCE($id: ID!) {
    source(id: $id) {
        data {
            id
            attributes {
                title
                content
                publisher {
                    data {
                        attributes {
                            name
                            site
                        }
                    }
                }
                source
                summary
                createdAt
            }
        }
    }
}
