query GET_ALL_SOURCES {
    sources {
        data {
            id
            attributes {
                title
                content
                createdAt
                thumbnail {
                    data {
                        attributes {
                            url
                        }
                    }
                }

                publisher {
                    data {
                        attributes {
                            name
                            site
                            logo {
                                data {
                                    attributes {
                                        url
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
